<?php

namespace Playground\Models;

use Core\AbstractModel;

class Sample extends AbstractModel
{
    public function __construct()
    {
        parent::__construct();
        $this->table = 'test';
        $this->primaryKey = 'id';
    }

    public function getByLastName($lastName)
    {
        return parent::getByLastName($lastName); // TODO: Change the autogenerated stub
    }
}