<?php

namespace Playground\Models;

use Core\AbstractModel;
use Core\Database;

class Sample extends AbstractModel
{
    protected $database;
    public function __construct(
        Database $database
    )
    {
        parent::__construct();
        $this->table = 'test';
        $this->primaryKey = 'id';
        $this->database = $database;
    }

    public function getByLastName($lastName)
    {
        return parent::getByLastName($lastName); // TODO: Change the autogenerated stub
    }
}